# Generated by Django 2.1.7 on 2019-02-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shouts', '0002_auto_20190222_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='shout_time',
            new_name='added',
        ),
    ]
