language: python

python:
  - "3.6"

addon:
  - postgresql: "9.6"

install:
  - pip install pipenv
  - pipenv install --skip-lock
script:
  - coverage run manage.py test auth --verbosity 3
  - coverage report -m
  - coveralls
after script:
  - coveralls