export const GET_CONTACTS='GET_CONTACTS';
export const DELETE_CONTACT='DELETE_CONTACT'
export const ADD_CONTACT='ADD_CONTACT';
export const GET_ERRORS='GET_ERRORS';
export const GET_MESSAGES='GET_MESSAGES';
export const CREATE_MESSAGE='CREATE_MESSAGE';
